version: "3.3"
services:
  api:
    build: api/
    ports:
    - "8081:8080"
    environment:
      db_host: "db"
    depends_on:
    - db
    restart: unless-stopped
  db:
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "127.0.0.1:5432:5432"
  frontend:
    build: frontend/
    ports:
    - "8080:8080"
    environment:
      api_base_url: "http://API:8080/"